name: Update Yahoo Finance Data

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1  # Only fetch latest commit, saves time

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install yfinance pandas openpyxl

    - name: Run update script
      run: python update.py

    - name: Push updated CSV/XLSX without committing history
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        # Reset index to overwrite history
        git checkout --orphan temp_branch
        git add YahooData.csv YahooData.xlsx
        git commit -m "Overwrite latest CSV/XLSX"
        git branch -D main
        git branch -m main
        git push -f https://x-access-token:${GITHUB_TOKEN}@github.com/b18d/finance-auto-update.git main
